export const SET_INFO_TEXT = 'SET_INFO_TEXT'
export const SET_SUBSCRIPTION_TEXT = 'SET_SUBSCRIPTION_TEXT'
export const SET_SUBSCRIBE_SUCCESS_TEXT = 'SET_SUBSCRIBE_SUCCESS_TEXT'
export const SET_CREDIT_LINKS = 'SET_CREDIT_LINKS'
